name: Auto add GSSoC label to Pull Requests

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add GSSoC approved label to PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ["gssoc:approved"],
            });
            